### ISSUE TITLE
Invisible Surface Profiles Created

### ISSUE THREAD

**Issue by DeCodeEater** [evanthoms/Cross-Section#17]
Hello. Hope you're well
Tried using the cross section tool to created segmented surface profiles but after a success dialog nothing appears on my screen even if i zoom to layer. please how do i fix this?. Thank You
![Segmented surface profile](https://github.com/ethoms-usgs/Cross-Section/assets/117387202/80b55d21-86db-4d3d-899e-b28595693bdc)
![NO SEGLINE](https://github.com/ethoms-usgs/Cross-Section/assets/117387202/b839704c-504d-4083-807e-ab70a1d5d4d4)

**Comment by ethoms-usgs** [comment]
Hard to say. First. make sure all your source data are in the same coordinate system. Second, make sure your line of cross section lies fully within the boundary of your dem. Third, check the intermediate datasets. I think these get written your default geodatabase. They have names that end in '_z', '_zm', '_polyEvents', '_located', and '_profiles'. You might be able to figure out where the tool starts writing empty feature clases. 

That said, I don't maintain this repo at all anymore and don't have access to ArcMap; I should probably take it down. Most of the code, excluding borehole plotting, has been moved to the xs-update branch of the [GeMS Toolbox](https://github.com/DOI-USGS/gems-tools-pro/tree/xs-update), so I hope you have access to ArcGIS Pro.

Finally, I will be out of the office until July 1. I may be able to help more when I return.

**Comment by DeCodeEater** [comment]
Thank You.
